repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        exclude: ^frontend/
      # Run the formatter
      - id: ruff-format
        exclude: ^frontend/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^frontend/
      - id: end-of-file-fixer
        exclude: ^frontend/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
